### PR TITLE
add(cauliflower with meat cover)

### PR DESCRIPTION
**Pull request by karlnyr**
### This PR adds:
- Cauliflower with meat cover to the 80's delicacies category

**How to prepare for test**:

### How to test:
- deploy to stage

### Expected outcome:
- [ ] Cauliflower with meat cover is displayed

### Review:
- [ ] Code approved by
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by northwestwitch — APPROVED** [review]
AHH I love vintage food! I might even have the same recipe book somewhere (bought it in a loppis, it's cards, not an actual book).

Works perfectly, good job! 👍🏻 

image

**Comment by northwestwitch** [comment]
I think this one is good to merge @karlnyr

**Comment by karlnyr** [comment]
I have to admit that the recipe is a good idea, but the fact is that I winged all the timers in this recipe. I will close this PR - to avoid food poisoning of CG staff.

**Comment by northwestwitch** [comment]
Ok! :)

**Pull request closed without merging**
